config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    resources :grandparents, only: [:index, :new, :create]
  end
  root to: "pages#home"

  resources :grandparents do
    resources :bookings, only: [:new, :create, :index, :show ]
  end
  resources :bookings, only: [] do
    collection do
      get :my_bookings
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :grandparent
  belongs_to :user

  validates :start_time, :end_time, presence: true
end

app/models/grandparent.rb
class Grandparent < ApplicationRecord
  belongs_to :user
  has_many_attached :photos

  validates :skill, :description, :price, :experience, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :grandparent, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :address, :photo])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :address, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_grandparent, only: %i[new create]

  def index
    @grandparent = Grandparent.find(params[:grandparent_id])
    @bookings = Booking.all
    @grandparents_bookings = Booking.where(grandparent_id: params[:grandparent_id])
  end

  def new
    @grandparent = Grandparent.find(params[:grandparent_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.grandparent = @grandparent
    @booking.user = current_user
    if @booking.save
      redirect_to grandparent_path(@grandparent), notice: 'Booking was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def my_bookings
    @bookings = Booking.where(user_id: current_user.id)
  end

  private

  def set_grandparent
    @grandparent = Grandparent.find(params[:grandparent_id])
  end

  def booking_params
    params.require(:booking).permit(:start_time, :end_time)
  end
end

app/controllers/grandparents_controller.rb
class GrandparentsController < ApplicationController
  def index
    @grandparents_location = Grandparent.all
    @user_location = User.where.associated(:grandparent)
    @markers = User.all.geocoded.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude,
        grandparent: user.grandparent
      }
    end

    if params.dig(:filter, :skill).present?
      @grandparents = Grandparent.where(skill: params[:filter][:skill])

    else
      @grandparents = Grandparent.all
    end
  end

  def show
    @grandparent = Grandparent.find(params[:id])
  end

  def new
    @user = current_user
    @grandparent = Grandparent.new
  end

  def create
    @grandparent = Grandparent.new(grandparent_params)
    @grandparent.user = current_user
    if @grandparent.save
      redirect_to grandparent_path(@grandparent), notice: 'Grandparent was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def grandparent_params
    params.require(:grandparent).permit(:skill, :description, :price, :experience, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1 class="bookings">Bookings</h1>


<div class="bookings-container">
  <% @grandparents_bookings.each do |booking| %>
    <div class="time">
      <% if booking %>
        <p>Booking: <%= booking.id %></p>
        <p>Grandparent: <%= booking.grandparent.user.first_name %> <%= booking.grandparent.user.last_name %></p>
        <p>Student: <%= booking.user.first_name %> <%= booking.user.last_name %></p>
        <p>Booking date: <%= booking.start_time.to_date.to_formatted_s(:rfc822)%></p>
        <p>Booking time: <%= booking.start_time.strftime("%I:%M%p")%></p>
      <% else %>
        <p>No bookings</p>
      <% end %>
    </div>
  <% end %>
</div>
<div class="back">
  <%= link_to "Back to #{@grandparent.user.first_name}'s Profile", grandparent_path(@grandparent), class: "button" %>
</div>

app/views/bookings/my_bookings.html.erb
<h1>My bookings</h1>

<div class="bookings-container">
  <% @bookings.each do |booking| %>
    <div class="time">
      <% if booking %>
        <p>Booking: <%= booking.id %></p>
        <p>Grandparent: <%= booking.grandparent.user.first_name %> <%= booking.grandparent.user.last_name %></p>
        <p>Student: <%= booking.user.first_name %> <%= booking.user.last_name %></p>
        <p>Booking date: <%= booking.start_time.to_date.to_formatted_s(:rfc822)%></p>
        <p>Booking time: <%= booking.start_time.strftime("%I:%M%p")%></p>
      <% else %>
        <p>No bookings</p>
      <% end %>
    </div>
  <% end %>
</div>

<div class="back">
  <%= link_to "Back to home", root_path, class: "button" %>
</div>

app/views/bookings/new.html.erb
<div class="new-booking">
  <h1>New Booking</h1>
  <%= simple_form_for [@grandparent, @booking], html: { data: { controller: "datepicker" } } do |f| %>
    <%= f.input :start_time,
            as: :string,
            input_html: { class: "datepicker", data: { datepicker_target: "start" } }%>
    <%= f.input :end_time,
            as: :string,
            input_html: { class: "datepicker", data: { datepicker_target: "end" } }%>
    <%= f.submit "Submit Booking", class: "button" %>
  <% end %>
  <%= link_to "Back to #{@grandparent.user.first_name}'s Profile", grandparent_path(@grandparent), class: "button" %>
</div>

app/views/grandparents/index.html.erb
<div class="map-cards">
  <div class="container justify-content-center">
    <%= simple_form_for :filter, url: grandparents_path, method: :get do |f| %>
      <%= f.input :skill, collection: Grandparent.all.pluck(:skill) %>
      <%= f.submit %>
    <% end %>


    <div class="grandparents-cards-container">
        <% @grandparents.each do |grandparent| %>
          <%= link_to grandparent_path(grandparent), class: "text-decoration-none" do %>
          <div class="card m-2">
          <%if grandparent.user.photo.key == nil %>
            <%= image_tag "https://res.cloudinary.com/dpt8iwr4k/image/upload/v1748533518/blank-profile-picture_xdu3re.webp", alt: "profile photo" %>
          <% else %>
              <%= cl_image_tag grandparent.user.photo.key, class: "card-photo", alt: "grandparent photo" %>
          <% end %>
            <div class="card-info">
              <h5 class="card-title"><%= grandparent.user.first_name %> <%= grandparent.user.last_name %></h5>
            </div>
            <div class="card-info">
              <div>
                <p>Skill: <%= grandparent.skill %></p>
              </div>
              <p>Price: £<%= grandparent.price %>/hr</p>
            </div>
          </div>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="map"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/grandparents/new.html.erb
<div class="new-grandparent container mt-3 justify-content-center bg-light px-5 py-4 rounded-3 shadow">
  <h2 class="fw-bolder mt-0 mb-4">Create a profile:</h1>
  <%= simple_form_for(@grandparent) do |f| %>
    <%= f.input :skill, label: "What skill would you like to teach?" %>
    <%= f.input :description, label: "Tell us some background information about yourself and your skill:", as: :text, input_html: { rows: 5, cols: 50 }  %>
    <div class="d-flex align-items-center">
      <div data-controller="range" class="mb-3 container d-flex flex-column align-items-center">
        <%= f.input :price, as: :integer, label: "How much would you like to charge per hour?",
            input_html: {
              type: "range",
              min: 0,
              max: 50,
              step: 1,
              value: 0,
              data: { range_target: "slider", action: "input->range#update" }
            } %>
        <div class="d-flex align-items-center">
          <span>Price:</span>
          <span class="ms-2 fw-bolder">£</span>
          <span class="fw-bolder" data-range-target="output"><%= @grandparent.price || 0 %></span>
        </div>
      </div>
      <div data-controller="range" class="mb-3 container d-flex flex-column align-items-center">
        <%= f.input :experience, as: :integer, label: "How many years of experience do you have in your skill?",
            input_html: {
              type: "range",
              min: 0,
              max: 50,
              step: 5,
              value: 0,
              data: { range_target: "slider", action: "input->range#update" }
            } %>
        <div class="d-flex align-items-center">
          <span>Years:</span>
          <span class="ms-2 fw-bolder" data-range-target="output"><%= @grandparent.experience || 0 %></span>
        </div>
      </div>
    </div>

    <%= f.input :photos, label: "Upload a few photo of yourself", as: :file, input_html: {multiple: true}  %>
    <%= f.submit "Create Grandparent Page", class: "button" %>
  <% end %>
  <%= link_to "Back to Home", root_path, class: "button" %>
</div>

app/views/grandparents/show.html.erb
<div class="full-page">


<div class="grandparent-container">
  <div class="image-layout">
    <% @grandparent.photos.each do |photo| %>
      <%= cl_image_tag photo.key, class: "multiple-img" %>
    <% end %>
  </div>
  <div class="name">
  <h1><u><%= @grandparent.user.first_name %> <%= @grandparent.user.last_name %></u></h1>
  </div>
  <div class="grandparent-details">
    <h4>Details:</h4>
    <p>Skill: <%= @grandparent.skill %></p>
    <p>Price: £<%= @grandparent.price %>/hr</p>
    <p>Years of experience: <%= @grandparent.experience %></p>
    <h4>Description:</h4>
    <p><%= @grandparent.description %></p>
  </div>
    <br>
  <div class="buttons">
    <%= link_to "View #{@grandparent.user.first_name}'s bookings", grandparent_bookings_path(@grandparent), class: "button" %>
    <%= link_to "Book #{@grandparent.user.first_name}", new_grandparent_booking_path(@grandparent), class: "button"  %>
  <p><%= image_tag "https://res.cloudinary.com/dpt8iwr4k/image/upload/v1748614169/back_isc0mn.png" %> Back to list of grandparents</p>
    <%=link_to  grandparents_path, class: "back" do %>
  <% end %>
  </div>
</div>
<div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NannyMchire</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url('<%= asset_path('elderly6.jpg') %>'), linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4))">
  <div class="container">
    <h1 class="fw-bold">Grandparents need you just as much as you need them</h1>
    <%= link_to "Hire now", grandparents_path, class: "btn btn-light mt-3 rounded-3" %>
    <%= link_to "Create a grandparent profile", new_grandparent_path, class: "btn btn-light mt-3 rounded-3" %>
  </div>
</div>

<div class="container my-5">
  <h2 class="fw-bold mb-3 text-center">About Us</h2>
  <p>Grandparents have more hobbies and superpowers than you can imagine - from mastering the perfect Sunday roast and cooking a full English breakfast, to passing down secret knitting techniques and legendary garden tricks. Some know how to build rockets, fix airplanes, or at least explain exactly how it should be done - often with a cup of tea and a brilliant story to go with it.NannyMcHire celebrates these everyday heroes by connecting them with younger generations eager to learn, laugh, and share time together.</p>
</div>
<div class="container my-5">
  <h2 class="mb-4 text-center fw-bold">Explore Our Wonderful Grandparent Profiles</h2>

  <div class="row row-cols-1 row-cols-md-3 g-4 justify-content-center">

    <!-- Card 1 -->
    <div class="col d-flex justify-content-center">
      <div class="card h-100" style="width: 18rem;">

        <div class="card-body">
          <h5 class="card-title fw-bold">Benedict Rees-Mogg</h5>
          <p class="text-muted">Architecture & Engineering</p>
          <p class="card-text">Architect and engineer with over 15 years' experience, keen to share his passion with budding young minds.</p>
        </div>
      </div>
    </div>

    <!-- Card 2 -->
    <div class="col d-flex justify-content-center">
      <div class="card h-100" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title fw-bold">Charlotte Hayes</h5>
          <p class="text-muted">Jewellery Design</p>
          <p class="card-text">With 10+ years in jewellery design, Charlotte delights in teaching others how to craft their own treasures.</p>
        </div>
      </div>
    </div>

    <!-- Card 3 -->
    <div class="col d-flex justify-content-center">
      <div class="card h-100" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title fw-bold">Wasaki Wafula</h5>
          <p class="text-muted">Electric Guitar Playing</p>
          <p class="card-text">Wasaki brings 35 years of rock ‘n’ roll energy, perfect for those ready to strike their first chord.</p>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-dark text-white py-4 mt-5">
  <div class="container text-center">
    <p>&copy; <%= Time.current.year %> All rights reserved.</p>
    <p class="mb-0">Made with love by Roadies at Le Wagon London.</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag("Nanny-McHire-No-Name.png", class: "own-logo") %>
   <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= image_tag("Nanny-McHire-Name-Only-Tagline.png", class: "title-img") %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "About", root_path, class: "nav-link" %>
          </li>


          <li class="nav-item dropdown">

          <%if current_user.photo.key == nil %>
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "https://res.cloudinary.com/dpt8iwr4k/image/upload/v1748533518/blank-profile-picture_xdu3re.webp", class: "avatar", alt: "dropdown menu" %>
          <% else %>
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
          <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My bookings", my_bookings_bookings_path, class: "nav-link" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>